from django.utils.translation import ugettext_lazy as _

from base import conf

CFGSERVER_PREFIX = "CFGSERVER"

CFGSERVER_VERBOSE_NAME = _("CfgServer")
CFGSERVER_VERBOSE_NAME_PLURAL = _("CfgServer")

CFGSERVER_LIST_URL_NAME = CFGSERVER_PREFIX + conf.LIST_SUFFIX
CFGSERVER_CREATE_URL_NAME = CFGSERVER_PREFIX + conf.CREATE_SUFFIX
CFGSERVER_DETAIL_URL_NAME = CFGSERVER_PREFIX + conf.DETAIL_SUFFIX
CFGSERVER_UPDATE_URL_NAME = CFGSERVER_PREFIX + conf.UPDATE_SUFFIX
CFGSERVER_DELETE_URL_NAME = CFGSERVER_PREFIX + conf.DELETE_SUFFIX

CFGCOLORS_PREFIX = "CFGCOLORS"

CFGCOLORS_VERBOSE_NAME = _("CfgColors")
CFGCOLORS_VERBOSE_NAME_PLURAL = _("CfgColors")

CFGCOLORS_LIST_URL_NAME = CFGCOLORS_PREFIX + conf.LIST_SUFFIX
CFGCOLORS_CREATE_URL_NAME = CFGCOLORS_PREFIX + conf.CREATE_SUFFIX
CFGCOLORS_DETAIL_URL_NAME = CFGCOLORS_PREFIX + conf.DETAIL_SUFFIX
CFGCOLORS_UPDATE_URL_NAME = CFGCOLORS_PREFIX + conf.UPDATE_SUFFIX
CFGCOLORS_DELETE_URL_NAME = CFGCOLORS_PREFIX + conf.DELETE_SUFFIX

CFGCONFIG_PREFIX = "CFGCONFIG"

CFGCONFIG_VERBOSE_NAME = _("CfgConfig")
CFGCONFIG_VERBOSE_NAME_PLURAL = _("CfgConfig")

CFGCONFIG_LIST_URL_NAME = CFGCONFIG_PREFIX + conf.LIST_SUFFIX
CFGCONFIG_CREATE_URL_NAME = CFGCONFIG_PREFIX + conf.CREATE_SUFFIX
CFGCONFIG_DETAIL_URL_NAME = CFGCONFIG_PREFIX + conf.DETAIL_SUFFIX
CFGCONFIG_UPDATE_URL_NAME = CFGCONFIG_PREFIX + conf.UPDATE_SUFFIX
CFGCONFIG_DELETE_URL_NAME = CFGCONFIG_PREFIX + conf.DELETE_SUFFIX
