create table cfg_overviewqueries
(
    id              int auto_increment
        primary key,
    name            varchar(35)      not null,
    query_v5        varchar(255)     not null,
    query_v6        varchar(255)     not null,
    unit            varchar(10)      not null,
    alert_comp      varchar(35)      not null,
    alert_val       varchar(35)      not null,
    alert_col       varchar(35)      not null,
    notforlibclient int(1) default 0 not null,
    pollfreq        int              not null,
    parent          varchar(35)      not null,
    sortorder       tinyint          not null
)
    collate = utf8_unicode_ci;

INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (1, 'Total Data stored', 'SELECT CAST(FLOAT(SUM(logical_mb)) / 1024 / 1024 AS DEC(8,3)) FROM occupancy', 'SELECT CAST(FLOAT(SUM(logical_mb)) / 1024 / 1024 AS DEC(8,3)) FROM occupancy', 'TB', '', '', '', 0, 3, 'totaldata', 10);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (2, 'Total Data backuped', 'SELECT cast(float(sum(bytes))/1024/1024/1024/1024 as dec(8,3)) FROM SUMMARY WHERE ACTIVITY=''BACKUP'' AND (CURRENT_TIMESTAMP-END_TIME)HOURS LESS= 24 HOURS', 'select ''N/A'' from status', 'TB', '', '', '', 0, 3, 'totaldata', 20);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (3, 'Total Data archived', 'SELECT cast(float(sum(bytes))/1024/1024/1024/1024 as dec(8,3)) FROM SUMMARY WHERE ACTIVITY=''ARCHIVE'' AND (CURRENT_TIMESTAMP-END_TIME)HOURS LESS= 24 HOURS', 'select ''N/A'' from status', 'TB', '', '', '', 0, 3, 'totaldata', 30);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (4, 'Scratch Tapes', 'SELECT COUNT(*) FROM libvolumes WHERE status=''Scratch''', 'SELECT COUNT(*) FROM libvolumes WHERE status=''Scratch''', '', 'less', '10', 'alarm', 1, 3, 'healthdata', 10);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (5, 'Volumes with Errors', 'SELECT COUNT(*) FROM volumes WHERE error_state=''YES''', 'SELECT COUNT(*) FROM volumes WHERE error_state=''YES''', '', 'more', '0', 'alarm', 0, 3, 'healthdata', 20);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (6, 'Unavailable Volumes', 'SELECT COUNT(*) FROM volumes WHERE access=''UNAVAILABLE''', 'SELECT COUNT(*) FROM volumes WHERE access=''UNAVAILABLE''', '', 'more', '0', 'alarm', 0, 3, 'healthdata', 30);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (7, 'Drives Offline', 'SELECT COUNT(*) FROM drives WHERE NOT online=''YES''', 'SELECT COUNT(*) FROM drives WHERE NOT online=''YES''', '', 'more', '0', 'alarm', 1, 3, 'healthdata', 40);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (8, 'Paths Offline', 'SELECT COUNT(*) FROM paths WHERE NOT online=''YES''', 'SELECT COUNT(*) FROM paths WHERE NOT online=''YES''', '', 'more', '0', 'alarm', 1, 3, 'healthdata', 50);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (9, 'Cache Hit', 'SELECT CACHE_HIT_PCT from db', 'SELECT BUFF_HIT_RATIO from db', '%', 'less', '98.0', 'warn', 0, 3, 'database', 10);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (10, 'Database Usage', 'SELECT pct_utilized FROM db', 'select used_db_space_mb*100/free_space_mb from db', '%', 'more', '90.0', 'alarm', 0, 3, 'database', 20);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (11, 'Log Usage', 'SELECT pct_utilized FROM log', 'select used_space_mb*100/free_space_mb from log', '%', 'more', '90.0', 'alarm', 0, 3, 'database', 30);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (12, 'DB Fragmentation', 'SELECT CAST((100 - (CAST(MAX_REDUCTION_MB AS FLOAT) * 256 ) / (CAST(USABLE_PAGES AS FLOAT) - CAST(USED_PAGES AS FLOAT) ) * 100) AS DECIMAL(4,2)) AS PERCENT_FRAG FROM DB', 'select ''N/A'' from status', '%', 'more', '10.0', 'alarm', 0, 3, 'database', 40);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (13, 'DB Volumes not synced', 'SELECT COUNT(*) FROM dbvolumes WHERE ( NOT copy1_status=''Synchronized'' OR NOT copy2_status=''Synchronized'' OR NOT copy3_status=''Synchronized'')', 'select ''N/A'' from status', '', 'more', '0', 'alarm', 0, 3, 'database', 50);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (14, 'DB Logs not synced', 'SELECT COUNT(*) FROM logvolumes WHERE ( NOT copy1_status=''Synchronized'' OR NOT copy2_status=''Synchronized'' OR NOT copy3_status=''Synchronized'')', 'select ''N/A'' from status', '', 'more', '0', 'alarm', 0, 3, 'database', 60);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (15, 'Last DB Backup', 'SELECT last_backup_date FROM db', 'SELECT last_backup_date FROM db', '', '', '', '', 0, 3, 'database', 70);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (16, 'Failed Admin Schedules', 'SELECT count(*) FROM events WHERE status NOTEQUAL ''Completed'' AND status NOTEQUAL ''Future'' AND status NOTEQUAL ''Started'' AND status NOTEQUAL ''Restarted'' and status NOTEQUAL ''In Progres'' and status NOTEQUAL ''Pending'' and NODE_NAME is NULL', 'SELECT count(*) FROM events WHERE status <> ''Completed'' AND status <> ''Future'' AND status <> ''Started'' AND status <> ''Restarted'' and status <> ''In Progres'' and status <> ''Pending'' AND NODE_NAME is NOT NULL', '', 'more', '0', 'alarm', 0, 3, 'schedules', 10);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (17, 'Failed Client Schedules', 'SELECT count(*) FROM events WHERE status NOTEQUAL ''Completed'' AND status NOTEQUAL ''Future'' AND status NOTEQUAL ''Started'' AND status NOTEQUAL ''Restarted'' and status NOTEQUAL ''In Progres'' and status NOTEQUAL ''Pending'' AND NODE_NAME is NOT NULL', 'SELECT count(*) FROM events WHERE status NOTEQUAL ''Completed'' AND status NOTEQUAL ''Future'' AND status NOTEQUAL ''Started'' AND status NOTEQUAL ''Restarted'' and status NOTEQUAL ''In Progres'' and status NOTEQUAL ''Pending'' AND NODE_NAME is NOT NULL', '', 'more', '0', 'alarm', 0, 3, 'schedules', 20);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (18, 'Running Client Schedules', 'SELECT count(*) FROM events WHERE status NOTEQUAL ''Completed'' AND status NOTEQUAL ''Future'' AND (status=''In Progres'' OR status=''Started'' OR status=''Restarted'') and NODE_NAME is NOT NULL', 'SELECT count(*) FROM events WHERE status <> ''Completed'' AND status <> ''Future'' AND (status=''In Progres'' OR status=''Started'' OR status=''Restarted'') and NODE_NAME is NOT NULL', '', 'more', '0', 'warn', 0, 3, 'schedules', 30);
INSERT INTO tsmmonitor.cfg_overviewqueries (id, name, query_v5, query_v6, unit, alert_comp, alert_val, alert_col, notforlibclient, pollfreq, parent, sortorder) VALUES (19, 'Running Admin Schedules', 'SELECT count(*) FROM events WHERE status NOTEQUAL ''Completed'' AND status NOTEQUAL ''Future'' AND (status=''In Progre%'' OR status=''Started'' OR status=''Restarted'') and NODE_NAME is NULL', 'SELECT count(*) FROM events WHERE status <> ''Completed'' AND status <> ''Future'' AND (status=''In Progre%'' OR status=''Started'' OR status=''Restarted'') and NODE_NAME is NULL', '', 'more', '0', 'warn', 0, 3, 'schedules', 40);