# Generated by Django 3.0.1 on 2019-12-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytsm', '0002_auto_20191226_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgoverviewbox',
            name='label',
            field=models.CharField(default='label', help_text='Label for the visible HTML page.', max_length=35, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='cfgoverviewbox',
            name='name',
            field=models.CharField(default='CFG_', help_text='Name that is used internally.', max_length=35, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='cfgoverviewbox',
            name='sortorder',
            field=models.SmallIntegerField(default=10, help_text='Sort order of the output.', verbose_name='Sort'),
        ),
        migrations.AlterField(
            model_name='cfgmainmenu',
            name='label',
            field=models.CharField(default='label', help_text='Label for the visible HTML page.', max_length=35, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='cfgmainmenu',
            name='name',
            field=models.CharField(default='CFG_', help_text='Name that is used internally.', max_length=35, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cfgmainmenu',
            name='sortorder',
            field=models.SmallIntegerField(default=10, help_text='Sort order of the output.', verbose_name='Sort'),
        ),
    ]
