# Generated by Django 3.0.1 on 2019-12-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytsm', '0003_auto_20191226_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.CharField(help_text='', max_length=35, verbose_name='Servername')),
                ('pid', models.IntegerField(help_text='', null=True, verbose_name='Pid')),
                ('status', models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status')),
                ('lastrun', models.DateTimeField(help_text='', verbose_name='Lastrun')),
                ('nextrun', models.DateTimeField(help_text='', verbose_name='Nextrun')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'job_list',
            },
        ),
    ]
