# Generated by Django 3.0.1 on 2019-12-26 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytsm', '0005_auto_20191226_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='lastrun',
            field=models.DateTimeField(help_text='', verbose_name='Lastrun'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='nextrun',
            field=models.DateTimeField(help_text='', verbose_name='Nextrun'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='pid',
            field=models.IntegerField(help_text='', null=True, verbose_name='Pid'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='servername',
            field=models.CharField(help_text='', max_length=35, verbose_name='Servername'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='status',
            field=models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CfgOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CFG_', help_text='Name that is used internally.', max_length=35, unique=True, verbose_name='Name')),
                ('label', models.CharField(default='label', help_text='Label for the visible HTML page.', max_length=35, verbose_name='Label')),
                ('sortorder', models.SmallIntegerField(default=10, help_text='Sort order of the output.', verbose_name='Sort')),
                ('alert_cmp', models.CharField(blank=True, help_text='Set alarm compare.', max_length=35, null=True, verbose_name='Alert Compare')),
                ('alert_val', models.CharField(blank=True, help_text='Set alarm value.', max_length=35, null=True, verbose_name='Alert Value')),
                ('alert_col', models.CharField(blank=True, help_text='Comparison field for the alarm', max_length=35, null=True, verbose_name='Alert Column')),
                ('query', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('notforlibclient', models.BooleanField(default=False)),
                ('pollfreq', models.PositiveSmallIntegerField(default=200)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pytsm.CfgOverviewbox')),
            ],
            options={
                'verbose_name': 'Overviewquery',
                'verbose_name_plural': 'Overviewqueries',
                'db_table': 'cfg_overview',
            },
        ),
    ]
