# Generated by Django 3.0.1 on 2019-12-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytsm', '0007_auto_20191226_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(help_text='Tablename', max_length=255, unique=True, verbose_name='Tablename')),
                ('hash', models.CharField(help_text='MD5 Summe from tablename', max_length=255, null=True, verbose_name='HASH')),
            ],
            options={
                'verbose_name': 'Hash',
                'verbose_name_plural': 'Hashes',
                'db_table': 'log_hash',
            },
        ),
        migrations.CreateModel(
            name='LogPolldlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Timestamp create Tablename', verbose_name='Timestamp')),
                ('servername', models.CharField(help_text='Servername', max_length=30, verbose_name='Servername')),
                ('updated', models.DateTimeField(help_text='Last update of the table.', verbose_name='Updated')),
                ('not_changed', models.DateTimeField(help_text='Time span for how long no change has taken place.', verbose_name='Not Changed')),
                ('pollfreq_not_reached', models.DateTimeField(help_text='Repeat period has not yet been reached.', verbose_name='Pollfrequenz not reached')),
                ('timeneeded', models.DateTimeField(help_text='Time required for last job.', verbose_name='Timeneeded')),
            ],
            options={
                'verbose_name': 'PollDLog',
                'verbose_name_plural': 'PollDLogs',
                'db_table': 'log_polldlog',
            },
        ),
        migrations.CreateModel(
            name='LogPolldstat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='', verbose_name='Enabled')),
                ('status', models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status')),
                ('lastrun', models.DateTimeField(help_text='', verbose_name='Lastrun')),
                ('nextrun', models.DateTimeField(help_text='', verbose_name='Nextrun')),
            ],
            options={
                'verbose_name': 'PollDStatus',
                'verbose_name_plural': 'PollDStati',
                'db_table': 'log_polldstat',
            },
        ),
        migrations.AlterField(
            model_name='joblist',
            name='lastrun',
            field=models.DateTimeField(help_text='', verbose_name='Lastrun'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='nextrun',
            field=models.DateTimeField(help_text='', verbose_name='Nextrun'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='pid',
            field=models.IntegerField(help_text='', null=True, verbose_name='Pid'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='servername',
            field=models.CharField(help_text='', max_length=35, verbose_name='Servername'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='status',
            field=models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status'),
        ),
    ]
