# Generated by Django 3.0.1 on 2019-12-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytsm', '0012_auto_20191229_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cfgconfig',
            old_name='confkey',
            new_name='cfg_pytsm_config_confkey',
        ),
        migrations.RenameField(
            model_name='cfgconfig',
            old_name='confval',
            new_name='cfg_pytsm_config_confval',
        ),
        migrations.RenameField(
            model_name='cfgconfig',
            old_name='description',
            new_name='cfg_pytsm_config_description',
        ),
        migrations.RemoveField(
            model_name='cfgconfig',
            name='id',
        ),
        migrations.AddField(
            model_name='cfgconfig',
            name='cfg_pytsm_config_id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='lastrun',
            field=models.DateTimeField(help_text='', verbose_name='Lastrun'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='nextrun',
            field=models.DateTimeField(help_text='', verbose_name='Nextrun'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='pid',
            field=models.IntegerField(help_text='', null=True, verbose_name='Pid'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='servername',
            field=models.CharField(help_text='', max_length=35, verbose_name='Servername'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='status',
            field=models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='logpolldstat',
            name='enabled',
            field=models.BooleanField(default=True, help_text='', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='logpolldstat',
            name='lastrun',
            field=models.DateTimeField(help_text='', verbose_name='Lastrun'),
        ),
        migrations.AlterField(
            model_name='logpolldstat',
            name='nextrun',
            field=models.DateTimeField(help_text='', verbose_name='Nextrun'),
        ),
        migrations.AlterField(
            model_name='logpolldstat',
            name='status',
            field=models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status'),
        ),
    ]
