# Generated by Django 3.0.1 on 2019-12-29 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytsm', '0017_auto_20191229_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPytsmList',
            fields=[
                ('job_pytsm_list_id', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('job_pytsm_list_servername', models.CharField(help_text='', max_length=35, verbose_name='Servername')),
                ('job_pytsm_list_pid', models.IntegerField(help_text='', null=True, verbose_name='Pid')),
                ('job_pytsm_list_status', models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status')),
                ('job_pytsm_list_lastrun', models.DateTimeField(help_text='', verbose_name='Lastrun')),
                ('job_pytsm_list_nextrun', models.DateTimeField(help_text='', verbose_name='Nextrun')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'job_pytsm_list',
            },
        ),
        migrations.CreateModel(
            name='LogPytsmHash',
            fields=[
                ('log_pytsm_hash_id', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('log_pytsm_hash_tablename', models.CharField(help_text='Tablename', max_length=255, unique=True, verbose_name='Tablename')),
                ('log_pytsm_hash_hash', models.CharField(help_text='MD5 Summe from tablename', max_length=255, null=True, verbose_name='HASH')),
            ],
            options={
                'verbose_name': 'Hash',
                'verbose_name_plural': 'Hashes',
                'db_table': 'log_pytsm_hash',
            },
        ),
        migrations.CreateModel(
            name='LogPytsmPolldlog',
            fields=[
                ('log_pytsm_polldlog_id', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('log_pytsm_polldlog_timestamp', models.DateTimeField(help_text='Timestamp create Tablename', verbose_name='Timestamp')),
                ('log_pytsm_polldlog_servername', models.CharField(help_text='Servername', max_length=30, verbose_name='Servername')),
                ('log_pytsm_polldlog_updated', models.DateTimeField(help_text='Last update of the table.', verbose_name='Updated')),
                ('log_pytsm_polldlog_not_changed', models.DateTimeField(help_text='Time span for how long no change has taken place.', verbose_name='Not Changed')),
                ('log_pytsm_polldlog_pollfreq_not_reached', models.DateTimeField(help_text='Repeat period has not yet been reached.', verbose_name='Pollfrequenz not reached')),
                ('log_pytsm_polldlog_timeneeded', models.DateTimeField(help_text='Time required for last job.', verbose_name='Timeneeded')),
            ],
            options={
                'verbose_name': 'PollDLog',
                'verbose_name_plural': 'PollDLogs',
                'db_table': 'log_pytsm_polldlog',
            },
        ),
        migrations.CreateModel(
            name='LogPytsmPolldstat',
            fields=[
                ('log_pytsm_polldstat_id', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('log_pytsm_polldstat_enabled', models.BooleanField(default=True, help_text='', verbose_name='Enabled')),
                ('log_pytsm_polldstat_status', models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status')),
                ('log_pytsm_polldstat_lastrun', models.DateTimeField(help_text='', verbose_name='Lastrun')),
                ('log_pytsm_polldstat_nextrun', models.DateTimeField(help_text='', verbose_name='Nextrun')),
            ],
            options={
                'verbose_name': 'PollDStatus',
                'verbose_name_plural': 'PollDStati',
                'db_table': 'log_pytsm_polldstat',
            },
        ),
        migrations.DeleteModel(
            name='JobList',
        ),
        migrations.DeleteModel(
            name='LogHash',
        ),
        migrations.DeleteModel(
            name='LogPolldlog',
        ),
        migrations.DeleteModel(
            name='LogPolldstat',
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_notforlibclient',
            field=models.BooleanField(default=False, help_text='', verbose_name='Not for libclient.'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_parent',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, to='pytsm.CfgPytsmOverviewbox', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_pollfreq',
            field=models.PositiveSmallIntegerField(default=200, help_text='', verbose_name='poll freq.'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_query',
            field=models.CharField(help_text='', max_length=255, verbose_name='Overvie Query'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_unit',
            field=models.CharField(help_text='', max_length=10, null=True, verbose_name='Unit'),
        ),
    ]
