# Generated by Django 3.0.1 on 2019-12-29 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytsm', '0022_auto_20191229_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgpytsmcolors',
            name='cfg_pytsm_colors_id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cfgpytsmmainmenu',
            name='cfg_pytsm_mainmenu_id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_notforlibclient',
            field=models.BooleanField(default=False, help_text='', verbose_name='Not for libclient.'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_parent',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, to='pytsm.CfgPytsmOverviewbox', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_pollfreq',
            field=models.PositiveSmallIntegerField(default=200, help_text='', verbose_name='poll freq.'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_query',
            field=models.CharField(help_text='', max_length=255, verbose_name='Overvie Query'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_unit',
            field=models.CharField(help_text='', max_length=10, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverviewbox',
            name='cfg_pytsm_overviewbox_id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cfgpytsmserver',
            name='cfg_pytsm_server_id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_lastrun',
            field=models.DateTimeField(help_text='', verbose_name='Lastrun'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_nextrun',
            field=models.DateTimeField(help_text='', verbose_name='Nextrun'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_pid',
            field=models.IntegerField(help_text='', null=True, verbose_name='Pid'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_servername',
            field=models.CharField(help_text='', max_length=35, verbose_name='Servername'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_status',
            field=models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='logpytsmhash',
            name='log_pytsm_hash_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldlog',
            name='log_pytsm_polldlog_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_enabled',
            field=models.BooleanField(default=True, help_text='', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_lastrun',
            field=models.DateTimeField(help_text='', verbose_name='Lastrun'),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_nextrun',
            field=models.DateTimeField(help_text='', verbose_name='Nextrun'),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_status',
            field=models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status'),
        ),
    ]
