# Generated by Django 3.0.1 on 2019-12-29 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytsm', '0025_auto_20191229_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfgPytsmQueries',
            fields=[
                ('cfg_pytsm_queries_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cfg_pytsm_queries_tsmquery_v5', models.CharField(help_text='', max_length=500, verbose_name='TSM Query V5')),
                ('cfg_pytsm_queries_tsmquery_v6', models.CharField(help_text='', max_length=500, verbose_name='TSM Query V6')),
                ('cfg_pytsm_queries_fields', models.CharField(help_text='', max_length=1000, verbose_name='Query Fields')),
                ('cfg_pytsm_queries_timetablefields', models.CharField(blank=True, help_text='', max_length=255, null=True, verbose_name='Timetable Fields')),
                ('cfg_pytsm_queries_info', models.CharField(blank=True, help_text='', max_length=500, null=True, verbose_name='Info')),
                ('cfg_pytsm_queries_orderby', models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Order By')),
                ('cfg_pytsm_queries_notforlibclient', models.IntegerField(blank=True, help_text='', null=True, verbose_name='Not for lib client')),
                ('cfg_pytsm_queries_polltype', models.CharField(help_text='', max_length=35, verbose_name='Polltype')),
                ('cfg_pytsm_queries_pollfreq', models.IntegerField(help_text='', verbose_name='Pollfrequenz')),
                ('cfg_pytsm_queries_parent', models.CharField(help_text='', max_length=35, verbose_name='Parent ID')),
                ('cfg_pytsm_queries_sortorder', models.SmallIntegerField(help_text='', verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
                'db_table': 'cfg_pytsm_queries',
            },
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_notforlibclient',
            field=models.BooleanField(default=False, help_text='', verbose_name='Not for libclient.'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_parent',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, to='pytsm.CfgPytsmOverviewbox', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_pollfreq',
            field=models.PositiveSmallIntegerField(default=200, help_text='', verbose_name='poll freq.'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_query',
            field=models.CharField(help_text='', max_length=255, verbose_name='Overvie Query'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_unit',
            field=models.CharField(help_text='', max_length=10, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_lastrun',
            field=models.DateTimeField(help_text='', verbose_name='Lastrun'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_nextrun',
            field=models.DateTimeField(help_text='', verbose_name='Nextrun'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_pid',
            field=models.IntegerField(help_text='', null=True, verbose_name='Pid'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_servername',
            field=models.CharField(help_text='', max_length=35, verbose_name='Servername'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_status',
            field=models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_enabled',
            field=models.BooleanField(default=True, help_text='', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_lastrun',
            field=models.DateTimeField(help_text='', verbose_name='Lastrun'),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_nextrun',
            field=models.DateTimeField(help_text='', verbose_name='Nextrun'),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_status',
            field=models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status'),
        ),
    ]
