# Generated by Django 3.0.1 on 2019-12-30 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytsm', '0027_auto_20191229_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_notforlibclient',
            field=models.BooleanField(default=False, help_text='', verbose_name='Not for libclient.'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_parent',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, to='pytsm.CfgPytsmOverviewbox', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_pollfreq',
            field=models.PositiveSmallIntegerField(default=200, help_text='', verbose_name='poll freq.'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_query',
            field=models.CharField(help_text='', max_length=255, verbose_name='Overvie Query'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmoverview',
            name='cfg_pytsm_overview_unit',
            field=models.CharField(help_text='', max_length=10, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmqueries',
            name='cfg_pytsm_queries_fields',
            field=models.CharField(help_text='', max_length=1000, verbose_name='Query Fields'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmqueries',
            name='cfg_pytsm_queries_info',
            field=models.CharField(blank=True, help_text='', max_length=500, null=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmqueries',
            name='cfg_pytsm_queries_notforlibclient',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name='Not for lib client'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmqueries',
            name='cfg_pytsm_queries_orderby',
            field=models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Order By'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmqueries',
            name='cfg_pytsm_queries_parent',
            field=models.CharField(help_text='', max_length=35, verbose_name='Parent ID'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmqueries',
            name='cfg_pytsm_queries_pollfreq',
            field=models.IntegerField(help_text='', verbose_name='Pollfrequenz'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmqueries',
            name='cfg_pytsm_queries_polltype',
            field=models.CharField(help_text='', max_length=35, verbose_name='Polltype'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmqueries',
            name='cfg_pytsm_queries_sortorder',
            field=models.SmallIntegerField(blank=True, help_text='', null=True, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmqueries',
            name='cfg_pytsm_queries_timetablefields',
            field=models.CharField(blank=True, help_text='', max_length=255, null=True, verbose_name='Timetable Fields'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmqueries',
            name='cfg_pytsm_queries_tsmquery_v5',
            field=models.CharField(help_text='', max_length=500, verbose_name='TSM Query V5'),
        ),
        migrations.AlterField(
            model_name='cfgpytsmqueries',
            name='cfg_pytsm_queries_tsmquery_v6',
            field=models.CharField(help_text='', max_length=500, verbose_name='TSM Query V6'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_lastrun',
            field=models.DateTimeField(help_text='', verbose_name='Lastrun'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_nextrun',
            field=models.DateTimeField(help_text='', verbose_name='Nextrun'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_pid',
            field=models.IntegerField(help_text='', null=True, verbose_name='Pid'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_servername',
            field=models.CharField(help_text='', max_length=35, verbose_name='Servername'),
        ),
        migrations.AlterField(
            model_name='jobpytsmlist',
            name='job_pytsm_list_status',
            field=models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_enabled',
            field=models.BooleanField(default=True, help_text='', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_lastrun',
            field=models.DateTimeField(help_text='', verbose_name='Lastrun'),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_nextrun',
            field=models.DateTimeField(help_text='', verbose_name='Nextrun'),
        ),
        migrations.AlterField(
            model_name='logpytsmpolldstat',
            name='log_pytsm_polldstat_status',
            field=models.CharField(blank=True, help_text='', max_length=35, null=True, verbose_name='Status'),
        ),
    ]
